name: SDK-Gaming plugin
run-name: releasing packages 🚀

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node --version
      - run: npm install
      - run: sudo apt install fonts-ipafont fonts-ipaexfont
      - name: zip files
        run: |
          ${{ github.workspace }}/bin/build_simple.sh ${{ github.ref_name }}
      - run: ls -R build
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SDK-Gaming all plugnin package
          path: build/sdk-gaming-plugins-by-torichanjp-${{ github.ref_name }}.zip
      - run: echo "🍏 This job's status is ${{ job.status }}."

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: SDK-Gaming all plugnin package
          path: download/
      - name: List files in the repository
        run: |
          ls -R ${{ github.workspace }}
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "download/*"
          bodyFile: "release-note.md"
